import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import os from 'node:os';
import path from 'node:path';
import { readFile } from 'node:fs/promises';

const expected = JSON.parse(await readFile(new URL('./domain-architecture.json', import.meta.url), 'utf8'));

// Optional browser QA dependency, installed outside the repository.
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.VIEWER_PLAYWRIGHT_PATH || 'playwright');
const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  for (const width of [1366, 1920]) {
    await page.setViewportSize({ width, height: width === 1366 ? 768 : 1080 });
    await page.goto(process.env.VIEWER_URL || 'http://127.0.0.1:8091');
    await page.locator('#area-cards .area-card').first().waitFor();
    assert.equal(await page.locator('.workspace').isVisible(), false);
    assert.equal(await page.locator('#area-cards .area-card').count(), expected.areas.length);
    assert.match(await page.locator('#area-cards').innerText(), /Активный агрегат|активный агрегат/);
    await page.locator('#show-scenario').click();
    assert.match(await page.locator('#scenario-view').innerText(), /Удаление участника/);
    assert.match(await page.locator('#scenario-view').innerText(), /Техническая AST-трасса/);
    await page.locator('#scenario-view .scenario-step').first().locator('summary').click();
    assert.match(await page.locator('#scenario-view .scenario-step').first().innerText(), /_requireLifecycle/);
    await page.waitForURL(/step=/);
    await page.screenshot({ path: path.join(os.tmpdir(), `domain-viewer-scenario-${width}.png`) });
    await page.locator('#scenario-view [data-member]').first().click();
    assert.equal(await page.locator('#show-object').getAttribute('aria-pressed'), 'true');
    assert.match(await page.locator('#detail').innerText(), /Tournament/);
    await page.screenshot({ path: path.join(os.tmpdir(), `domain-viewer-object-${width}.png`) });
    await page.goBack();
    assert.equal(await page.locator('#show-scenario').getAttribute('aria-pressed'), 'true');
    await page.locator('#show-overview').click();
    await page.evaluate(() => window.scrollTo(0, document.querySelector('#area-overview').getBoundingClientRect().top + window.scrollY));
    await page.screenshot({ path: path.join(os.tmpdir(), `domain-viewer-overview-stage4-${width}.png`) });
    await page.locator('#area-connections .area-connection').first().locator('summary').click();
    await page.locator('#area-connections [data-relation]').first().click();
    await page.locator('#relation-evidence').waitFor();
    await page.locator('#relation-evidence .relation-occurrence').first().locator('summary').click();
    assert.match(await page.locator('#relation-evidence').innerText(), /resolved-single/);
    await page.locator('#show-map').click();
    await page.locator('.inventory-card').first().waitFor();
    assert.equal(await page.locator('.inventory-card').count(), expected.nodes.length);
    await page.locator('#search').fill('ProfileManagementPort');
    await page.locator('.inventory-card').filter({ has: page.locator('strong', { hasText: /^ProfileManagementPort$/ }) }).click();
    assert.match(await page.locator('#detail').innerText(), /Поиск реализации/);
    assert.match(await page.locator('#detail').innerText(), /delete/);
    assert.match(await page.locator('#detail').innerText(), /main\.dart/);
    await page.locator('#search').fill('RandomPort');
    await page.locator('.inventory-card').filter({ has: page.locator('strong', { hasText: /^RandomPort$/ }) }).click();
    assert.match(await page.locator('#detail').innerText(), /shuffled<T>/);
    await page.locator('#detail .member-fact').first().locator('summary').first().click();
    assert.match(await page.locator('#detail').innerText(), /объявление без тела/);
    await page.locator('#detail a').first().click();
    assert(page.url().includes('member='));
    await page.reload();
    await page.locator('#detail .member-fact[open]').waitFor();
    assert.match(await page.locator('#detail').innerText(), /shuffled<T>/);
    await page.locator('#show-map').click();
    await page.locator('#search').fill('Tournament');
    await page.locator('.inventory-card').filter({ has: page.locator('strong', { hasText: /^Tournament$/ }) }).click();
    assert.match(await page.locator('#detail').innerText(), /Операция: Tournament.removeParticipant/i);
    assert((await page.locator('#detail .member-fact').count()) > 30);
    await page.locator('#detail [data-relation]').filter({ hasText: /CharacterAssignmentSet.*Вызов метода/ }).first().click();
    assert.match(await page.locator('#relation-evidence').innerText(), /Tournament → CharacterAssignmentSet/);
    await page.locator('#relation-evidence .relation-occurrence').filter({ hasText: /removeParticipant/ }).first().locator('summary').click();
    assert.match(await page.locator('#relation-evidence').innerText(), /assignments\.remove\(participantId\)/);
    await page.locator('#show-map').click();
    await page.locator('#zoom-fit').click();
    await page.evaluate(() => window.scrollTo(0, document.querySelector('.workspace').getBoundingClientRect().top + window.scrollY));
    await page.screenshot({ path: path.join(os.tmpdir(), `domain-viewer-stage4-${width}.png`) });
  }
  await page.setViewportSize({ width: 720, height: 800 });
  await page.goto((process.env.VIEWER_URL || 'http://127.0.0.1:8091') + '/#view=object&object=' + encodeURIComponent(expected.nodes.find((node) => node.title === 'Tournament').id));
  await page.evaluate(() => { document.body.style.zoom = '2'; });
  assert.equal(await page.locator('#show-object').getAttribute('aria-pressed'), 'true');
  assert.match(await page.locator('#detail').innerText(), /Активный агрегат/);
  assert.equal(await page.locator('#detail').isVisible(), true);
  await page.locator('#show-map').click();
  assert.equal(await page.locator('.architecture-panel').isVisible(), true);
  await page.locator('#mobile-show-detail').click();
  assert.equal(await page.locator('#detail').isVisible(), true);
  await page.locator('#mobile-show-map').click();
  assert.equal(await page.locator('.architecture-panel').isVisible(), true);
  await page.goto(process.env.VIEWER_URL || 'http://127.0.0.1:8091');
  await page.locator('#area-cards .area-card').first().locator('summary').focus();
  await page.keyboard.press('Enter');
  const firstObject = page.locator('#area-cards .area-card').first().locator('[data-object]').first();
  await firstObject.focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('#show-object').getAttribute('aria-pressed'), 'true');
  assert.equal(await page.evaluate(() => document.activeElement?.tagName), 'H2');
  assert.deepEqual(errors, []);
  console.log('Browser QA passed: overview, area links, selected relation evidence, inventory, member permalink reload and operation trace at 1366/1920.');
} finally {
  await browser.close();
}
