import '../participant_identity/participant_identity.dart';
import 'bracket_view_data.dart';

BracketViewData previewBracketData(
  TournamentStructureFormat format,
) => switch (format) {
  TournamentStructureFormat.doubleElimination => BracketViewData(
    format: format,
    matches: [
      BracketMatchViewData(
        id: 'w1',
        title: 'Матч 01',
        lane: BracketLane.winners,
        round: 0,
        order: 0,
        first: previewParticipants[0],
        second: previewParticipants[1],
        state: BracketMatchState.won,
        resultLabel: 'Победитель: Scorpion · Иван',
      ),
      BracketMatchViewData(
        id: 'w2',
        title: 'Матч 02',
        lane: BracketLane.winners,
        round: 0,
        order: 1,
        first: previewParticipants[2],
        second: previewParticipants[3],
        state: BracketMatchState.won,
        resultLabel: 'Победитель: Raiden · Алекс',
      ),
      BracketMatchViewData(
        id: 'w3',
        title: 'Финал верхней сетки',
        lane: BracketLane.winners,
        round: 1,
        order: 0,
        first: previewParticipants[0],
        second: previewParticipants[3],
        state: BracketMatchState.current,
      ),
      BracketMatchViewData(
        id: 'l1',
        title: 'Матч 03',
        lane: BracketLane.losers,
        round: 0,
        order: 0,
        first: previewParticipants[1],
        second: previewParticipants[2],
        state: BracketMatchState.pending,
      ),
      BracketMatchViewData(
        id: 'l2',
        title: 'Финал нижней сетки',
        lane: BracketLane.losers,
        round: 1,
        order: 0,
        first: previewParticipants[1],
        second: previewParticipants[3],
        state: BracketMatchState.locked,
      ),
      BracketMatchViewData(
        id: 'gf',
        title: 'Grand Final',
        lane: BracketLane.finals,
        round: 2,
        order: 0,
        first: previewParticipants[0],
        second: previewParticipants[3],
        state: BracketMatchState.locked,
      ),
      BracketMatchViewData(
        id: 'reset',
        title: 'Grand Final · Bracket Reset',
        lane: BracketLane.finals,
        round: 3,
        order: 0,
        first: previewParticipants[0],
        second: previewParticipants[3],
        state: BracketMatchState.reset,
        conditionLabel:
            'Играется только если чемпион нижней сетки выиграет Grand Final',
      ),
    ],
    links: const [
      BracketLinkViewData(
        fromMatchId: 'w1',
        toMatchId: 'w3',
        label: 'Победитель Матча 01 переходит в финал верхней сетки',
      ),
      BracketLinkViewData(
        fromMatchId: 'w2',
        toMatchId: 'w3',
        label: 'Победитель Матча 02 переходит в финал верхней сетки',
      ),
      BracketLinkViewData(
        fromMatchId: 'w1',
        toMatchId: 'l1',
        label: 'Проигравший Матча 01 переходит в нижнюю сетку',
      ),
      BracketLinkViewData(
        fromMatchId: 'w2',
        toMatchId: 'l1',
        label: 'Проигравший Матча 02 переходит в нижнюю сетку',
      ),
      BracketLinkViewData(
        fromMatchId: 'l1',
        toMatchId: 'l2',
        label: 'Победитель Матча 03 переходит в финал нижней сетки',
      ),
      BracketLinkViewData(
        fromMatchId: 'w3',
        toMatchId: 'gf',
        label: 'Победитель верхней сетки переходит в Grand Final',
      ),
      BracketLinkViewData(
        fromMatchId: 'l2',
        toMatchId: 'gf',
        label: 'Победитель нижней сетки переходит в Grand Final',
      ),
      BracketLinkViewData(
        fromMatchId: 'gf',
        toMatchId: 'reset',
        label: 'Условный переход в Bracket Reset',
      ),
    ],
  ),
  TournamentStructureFormat.singleElimination => BracketViewData(
    format: format,
    matches: [
      BracketMatchViewData(
        id: 'se1',
        title: 'Матч 01 · Раунд 1',
        lane: BracketLane.stage,
        round: 0,
        order: 0,
        first: previewParticipants[0],
        second: previewParticipants[1],
        state: BracketMatchState.current,
      ),
      BracketMatchViewData(
        id: 'se2',
        title: 'Матч 02 · Раунд 1',
        lane: BracketLane.stage,
        round: 0,
        order: 1,
        first: previewParticipants[2],
        second: previewParticipants[3],
      ),
    ],
  ),
  TournamentStructureFormat.roundRobin => BracketViewData(
    format: format,
    matches: [
      BracketMatchViewData(
        id: 'rr1',
        title: 'Матч 01 · Общий этап',
        lane: BracketLane.stage,
        round: 0,
        order: 0,
        first: previewParticipants[0],
        second: previewParticipants[1],
        state: BracketMatchState.current,
      ),
      BracketMatchViewData(
        id: 'rr2',
        title: 'Матч 02 · Общий этап',
        lane: BracketLane.stage,
        round: 0,
        order: 1,
        first: previewParticipants[2],
        second: previewParticipants[3],
      ),
    ],
  ),
};
